name: Main CI-pipeline

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Checkstyle
        run: dotnet format --verify-no-changes
 
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true

      - name: Test with coverage
        run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Threshold=90 /p:ThresholdType=line /p:ThresholdStat=total

      - name: Coverage comment
        uses: bibipkins/dotnet-test-reporter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-path: ./**/coverage.cobertura.xml
          coverage-type: cobertura
          coverage-threshold: 90
